/*

-------Method---------

ALways follow best practices
:id in path is called params and some key values pair separated with '&' are called query
1. GET
--> URL - /todos
          /todo/:id
2. POST
--> URL - /todos
-->ReqB - Optional
3. PUT/PATCH
--> URL - /todos:/id
-->ReqB - Mandatory
4. Delete
--> URL - /todos:/id



-----------Header-----------

// Request Headers
1. Host: https://www.1d.example.com
2. Origin: https://www.example.com
3. Referer: Referer is an HTTP request header that tells a website where the user came from before visiting the current page.
4. User agent: is a string that a web browser or other client sends to a web server to identify itself and provide information about the client's operating system, browser version, and other details. It helps the server understand the client's capabilities and tailor responses accordingly.
5. Accept: The Accept header is an HTTP request header that specifies the media types (MIME types) that the client is willing to receive from the server in response to its request. It allows the client to indicate its preferred content types, such as JSON, HTML, XML, or plain text.
6. Accept-language: The Accept-Language header is an HTTP request header that indicates the preferred languages of the client for the response content. It allows the client to specify one or more languages it can understand, along with their relative preferences.
7. Accept-Encoding: The Accept-Encoding header is an HTTP request header that specifies the content encoding methods (compression algorithms) that the client can handle in the response. It allows the client to indicate its preferred encoding formats, such as gzip, deflate, or br (Brotli), which can help reduce the size of the response data and improve performance. 
8. Connection: The Connection header is an HTTP request header that controls whether the network connection should be kept open or closed after the current request/response cycle. It allows the client to specify its preference for maintaining a persistent connection (keep-alive) or closing the connection after the response is received.
9. Authorization: The Authorization header is an HTTP request header that is used to provide credentials or authentication information to access protected resources on the server. It allows the client to include authentication tokens, such as API keys, bearer tokens, or username/password combinations, to prove its identity and gain access to restricted endpoints.
10. Cookie: The Cookie header is an HTTP request header that allows the client to send cookies to the server. Cookies are small pieces of data stored on the client-side that can be used for session management, personalization, and tracking user behavior. The Cookie header contains key-value pairs representing the cookies associated with the domain of the requested resource.
11. Content-Type: The Content-Type header is an HTTP request header that indicates the media type (MIME type) of the request body being sent to the server. It informs the server about the format of the data being transmitted, allowing it to correctly interpret and process the request. Common values for the Content-Type header include application/json for JSON data, application/x-www-form-urlencoded for form data, multipart/form-data for file uploads, and text/plain for plain text.
12. Is-Modified-Since: The If-Modified-Since header is an HTTP request header that allows the client to make conditional requests based on the last modification date of a resource. It is used to optimize network bandwidth and improve performance by allowing the server to respond with a 304 Not Modified status code if the requested resource has not been modified since the specified date. This helps avoid unnecessary data transfer when the client already has a cached version of the resource.
13. Cache-Control: The Cache-Control header is an HTTP request header that allows the client to specify caching directives for the requested resource. It provides instructions to the server and intermediate caches on how to handle caching behavior. Common directives include no-cache (to bypass caching), max-age (to specify the maximum time a resource can be cached), and public/private (to indicate whether the resource can be cached by shared caches or only by the client).



// Response Headers
1. Date: The Date header is an HTTP response header that indicates the date and time at which the response was generated by the server. It provides information about when the server processed the request and can be useful for caching, logging, and debugging purposes.
2. server: The Server header is an HTTP response header that provides information about the software or server application that generated the response. It typically includes the name and version of the server software, such as Apache, Nginx, or Microsoft IIS. This header can be useful for identifying the server technology being used and for troubleshooting purposes.
3. Content-Type: The Content-Type header is an HTTP response header that indicates the media type (MIME type) of the response body being sent from the server to the client. It informs the client about the format of the data being transmitted, allowing it to correctly interpret and process the response. Common values for the Content-Type header include application/json for JSON data, text/html for HTML documents, text/plain for plain text, and application/xml for XML data.
4. Content-Length: The Content-Length header is an HTTP response header that indicates the size of the response body in bytes. It specifies the exact number of bytes that the client should expect to receive in the response. This header is important for clients to know how much data to read and can be used for progress tracking, buffering, and validating the completeness of the response.
5. Set-Cookie: The Set-Cookie header is an HTTP response header that allows the server to send cookies to the client. It instructs the client to store the specified cookie(s) and include them in subsequent requests to the same domain. The Set-Cookie header can include various attributes, such as the cookie name, value, expiration date, path, domain, and security flags (e.g., HttpOnly, Secure). Cookies are commonly used for session management, user authentication, personalization, and tracking user behavior across multiple requests.
6. Cache-Control: The Cache-Control header is an HTTP response header that allows the server to specify caching directives for the response. It provides instructions to the client and intermediate caches on how to handle caching behavior. Common directives include no-cache (to bypass caching), max-age (to specify the maximum time a resource can be cached), and public/private (to indicate whether the resource can be cached by shared caches or only by the client). The Cache-Control header helps optimize performance, reduce bandwidth usage, and ensure that clients receive fresh content when necessary.
7. Access-Control-Allow-Origin: The Access-Control-Allow-Origin header is an HTTP response header that is part of the Cross-Origin Resource Sharing (CORS) mechanism. It specifies which origins (domains) are allowed to access the resources on the server. When a client from a different origin makes a request to the server, the server includes this header in the response to indicate whether the request is permitted. The value of this header can be a specific origin (e.g., https://example.com) or a wildcard (*) to allow access from any origin. CORS is important for enabling secure cross-origin requests while preventing unauthorized access to resources.
8. Access-Control-Allow-Methods: The Access-Control-Allow-Methods header is an HTTP response header that is part of the Cross-Origin Resource Sharing (CORS) mechanism. It specifies the HTTP methods (e.g., GET, POST, PUT, DELETE) that are allowed when accessing the resources on the server from a different origin. When a client from a different origin makes a request to the server, the server includes this header in the response to indicate which methods are permitted for that particular resource. This helps enforce security and control over cross-origin requests.




// Status Codes

1. status range: 100-199
2. Use case: Informational responses
3. Status Code
    1. 100 Continue: The server has received the initial part of the request and the client should continue with the rest of the request.
    2. 101 Switching Protocols: The server is switching protocols as requested by the client.
    3. 102 Processing: The server has received and is processing the request, but no response is available yet.
    4. 103 Early Hints: The server is providing early hints to the client about resources that may be needed for the final response.


1. status range: 200-299
2. Use case: Successful responses
3. Status Code
    1. 200 OK: The request has succeeded.
    2. 201 Created: The request has been fulfilled and a new resource has been created.
    3. 202 Accepted: The request has been accepted for processing, but the processing has not been completed.
    4. 204 No Content: The server has successfully processed the request, but is not returning any content.
    5. 205 Reset Content: The server has successfully processed the request, but is not returning any content and requires the client to reset the document view.
    6. 206 Partial Content: The server is delivering only part of the resource due to a range header sent by the client. 


    
1. status range: 300-399
2. Use case: Redirection messages
3. Status Code
    1. 301 Moved Permanently: The requested resource has been permanently moved to a new URL.
    2. 302 Found: The requested resource has been temporarily moved to a different URL.
    3. 307 Temporary Redirect: The requested resource has been temporarily moved to a different URL, and the client should use the same HTTP method for the subsequent request.
    4. 304 Not Modified: The requested resource has not been modified since the last request, and the client can use the cached version of the resource.
    5. 308 Permanent Redirect: The requested resource has been permanently moved to a new URL, and the client should use the same HTTP method for the subsequent request.



1. status range: 400-499
2. Use case: Client Error messages
3. Status Code
    1. 400 Bad Request: The server cannot or will not process the request due to an apparent client error.
    2. 401 Unauthorized: The request requires user authentication.
    3. 403 Forbidden: The server understood the request, but is refusing to fulfill it.
    4. 404 Not Found: The requested resource could not be found on the server.
    5. 405 Method Not Allowed: The request method is not allowed for the requested resource.
    6. 409 Conflict: The request could not be completed due to a conflict with the current state of the resource.
    7. 422 Unprocessable Entity: The server understands the content type of the request entity, but was unable to process the contained instructions.
    8. 429 Too Many Requests: The user has sent too many requests in a given amount of time ("rate limiting").


1. status range: 500-599
2. Use case: Server Error messages
3. Status Code
    1. 500 Internal Server Error: The server encountered an unexpected condition that prevented it from fulfilling the request.
    2. 502 Bad Gateway: The server received an invalid response from an upstream server.
    3. 503 Service Unavailable: The server is currently unable to handle the request due to a temporary overload or maintenance.
    4. 504 Gateway Timeout: The server did not receive a timely response from an upstream server.
    5. 507 Insufficient Storage: The server is unable to store the representation needed to complete the request.
*/